---

platform: linux

params:
  DEBUG:
  ENV_FILE:

inputs:
- name: product
- name: pipelines-repo
- name: om-cli
- name: env

run:
  path: bash
  args:
  - "-c"
  - |
    if [[ $DEBUG == true ]]; then
      set -ex
    else
      set -e
    fi

    chmod +x om-cli/om-linux
    CMD=./om-cli/om-linux

    FILE_PATH=`find ./product -name *.pivotal`

    $CMD --env env/"${ENV_FILE}" upload-product -p $FILE_PATH
