resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: schedule
  type: time
  source:
    interval: 24h
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: tile-config-convertor
  type: github-release
  source:
    user: rahul-kj
    repository: tile-config-convertor
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: git-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: platform-automation-image
  type: docker-image
  source:
    repository: ((platform_automation_image_repository))

- name: buildbox-image
  type: docker-image
  source:
    repository: rjain/buildbox

- name: product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((product_slug))
    product_version: ((product_version))

- name: email
  type: email
  source:
    smtp:
      host: ((smtp_address))
      port: ((smtp_port))
      username: ((smtp_username))
      password: ((smtp_password))
    from: ((from_address))
    to: [((to_addresses))]

jobs:
- name: scheduler
  plan:
  - get: schedule
    trigger: true
  - get: product
    params:
      globs: []

- name: upload-and-stage-product
  serial: true
  plan:
  - aggregate:
    - get: git-repo
    - get: buildbox-image
    - get: platform-automation-image
    - get: product
      params:
        globs: [((product_glob))]
      passed: [scheduler]
      trigger: true
    - get: jq
      params:
        globs:
        - "*linux64*"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
    - get: om-cli
      params:
        globs:
        - "*-linux"

  - task: create-opsman-env-file
    image: buildbox-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: upload-and-stage-product
    image: platform-automation-image
    file: git-repo/tasks/upload-and-stage-product.yml
    input_mapping:
      product: product
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

  - task: download-stemcell
    image: buildbox-image
    file: git-repo/tasks/download-stemcell/task.yml
    input_mapping:
      product: product
    params:
      DEBUG: ((debug))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      STEMCELL_TYPE: ((stemcell_type))

  - task: upload-stemcell
    image: platform-automation-image
    file: git-repo/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: stemcells
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

- name: generate-config
  plan:
  - aggregate:
    - get: git-repo
      passed: [upload-and-stage-product]
    - get: pivnet-product
      resource: product
      params:
        globs: []
      passed: [upload-and-stage-product]
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [upload-and-stage-product]
    - get: tile-config-convertor
      params:
        globs: ["*linux*"]
    - get: buildbox-image
      passed: [upload-and-stage-product]

  - task: create-opsman-env-file
    image: buildbox-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: generate-config
    image: buildbox-image
    file: git-repo/tasks/generate-config/task.yml
    input_mapping:
      env: env
    params:
      DEBUG: ((debug))
      ENV_FILE: ((opsman_env_filename))
      PRODUCT_NAME: ((product_identifier))

- name: configure-product
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [upload-and-stage-product]
    - get: platform-automation-image
      passed: [upload-and-stage-product]
    - get: buildbox-image
      passed: [upload-and-stage-product]
    - get: product
      params:
        globs: []
      trigger: true
      passed: [upload-and-stage-product]

  - task: create-opsman-env-file
    image: buildbox-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: create-product-config-file
    image: buildbox-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: config
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: product-config.yml
      PARAM_NAME: ((product_config))

  - task: config-product
    image: platform-automation-image
    file: git-repo/tasks/configure-product.yml
    input_mapping:
      config: config
      env: env
    params:
      CONFIG_FILE: product-config.yml
      ENV_FILE: ((opsman_env_filename))

- name: deploy-product
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [configure-product]
    - get: platform-automation-image
      passed: [configure-product]
    - get: buildbox-image
      passed: [configure-product]
    - get: product
      params:
        globs: []
      trigger: true
      passed: [configure-product]

  - task: create-opsman-env-file
    image: buildbox-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: deploy-product
    image: platform-automation-image
    file: git-repo/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
