---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PIVNET_API_TOKEN:
  IAAS:
  IAAS_TYPE:
  STEMCELL_TYPE:

inputs:
- name: product

outputs:
- name: stemcells

run:
  path: bash
  args:
  - "-c"
  - |
    set -e

    PIVNET_CLI=pivnet
    JQ_CMD=jq

    SC_DETAILS=`cat ./product/metadata.json | $JQ_CMD -r '[.Dependencies[] | select(.Release.Product.Name | contains("Stemcells"))][0]'`

    SC_VERSION=$(echo "$SC_DETAILS" | $JQ_CMD -r '.Release.Version')
    PRODUCT_SLUG=$(echo "$SC_DETAILS" | $JQ_CMD -r '.Release.Product.Slug')

    echo "Downloading stemcell $SC_VERSION"
    $PIVNET_CLI login --api-token="$PIVNET_API_TOKEN"

    $PIVNET_CLI download-product-files -p $PRODUCT_SLUG -r $SC_VERSION -g "*$IAAS_TYPE*" --accept-eula -d stemcells
