---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:

inputs:
  - name: product
  - name: git-repo
  - name: govc

run:
  path: git-repo/tasks/generate-opsman-config/task.sh
