---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

inputs:
  - name: product

run:
  path: bash
  args:
  - "-c"
  - |
    set -e

    GOVC_CMD=govc

    FILE_PATH=`find ./product/ -name *.ova`

    $GOVC_CMD import.spec $FILE_PATH > import-spec.json

    ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))' < import-spec.json > import-spec.yml

    cat import-spec.yml

    rm import-spec*
