---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  ENV_FILE:
  APPLY_CHANGES_CONFIG: deploy-products.yml

inputs:
  - name: env
  - name: config

run:
  path: bash
  args:
  - "-c"
  - |
    OM_CMD=om

    if [[ ! -z "${APPLY_CHANGES_CONFIG}" && null != "${APPLY_CHANGES_CONFIG}" ]]; then
      $OM_CMD --env env/"${ENV_FILE}" apply-changes -c config/${APPLY_CHANGES_CONFIG})
    fi

    $OM_CMD --env env/"${ENV_FILE}" apply-changes --ignore-warnings true
