# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet export-installation start yaml
---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information

outputs:
- name: installation # will contain the exported installation

params:
  ENV_FILE: env.yml
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  INSTALLATION_FILE: installation.zip
  # - Optional
  # - Filepath of the installation ZIP file
  # - The path is relative to root of the `installation` output

run:
  path: bash
  args:
  - -c
  - |
    cat /var/version && echo ""
    set -eux
    om --env env/"${ENV_FILE}" export-installation \
       --output-file installation/"${INSTALLATION_FILE}"
# code_snippet export-installation end