#@data/values
---
separate_config: True
pivnet_token: ((pivnet_token))
automation_git_url: https://github.com/rahulkj/pcf-automation
automation_git_branch: master
config_repo_git_url: https://github.com/rahulkj/secrets
config_repo_git_branch: master
locks_git_url: https://github.com/rahulkj/pipeline-locks
locks_git_branch: master
env_lock_folder: pipeline-lock
git_username: ((git_credentials.username))
git_token: ((git_credentials.password))
credhub_prefix: concourse/homelab
credhub_ca_cert: ((credhub_server_ca.certificate))
credhub_client: ((credhub_client))
credhub_client_secret: ((credhub_client_secret))
credhub_server: ((credhub_server))
smtp_address: ((smtp_address))
smtp_port: ((smtp_port))
smtp_username: ((smtp_credentials.username))
smtp_password: ((smtp_credentials.password))
from_address: ((from_address))
to_addresses: ((to_addresses))
s3_endpoint: http://((s3_endpoint))/
s3_access_key: ((s3_credentials.username))
s3_secret_key: ((s3_credentials.password))
s3_disable_ssl: true
platform_automation_version: ^4\.*\..*$
s3_automation_bucket: automation
s3_automation_image_regex: image/platform-automation-image-(.*).tgz
s3_automation_tasks_regex: tasks/platform-automation-tasks-(.*).zip
apply_changes_config_filename: deploy-products.yml
products:
- name: pks
  slug: pivotal-container-service
  version: ^1\.7\..*$
  s3_bucket: pks
  s3_stemcell_bucket: stemcells
  s3_product_regex: "(.*).pivotal"
  s3_stemcell_regex: "bosh-stemcell-(.*).tgz"
  has_stemcell: True
- name: harbor
  slug: harbor-container-registry
  version: ^1\.10\..*$
  s3_bucket: harbor
  s3_stemcell_bucket: stemcells
  s3_product_regex: "(.*).pivotal"
  s3_stemcell_regex: "bosh-stemcell-(.*).tgz"
  has_stemcell: True

download_products:
- name: ops-manager
  has_stemcell: False
- name: pas
  has_stemcell: True
- name: pks
  has_stemcell: True
- name: harbor
  has_stemcell: True
- name: platform-automation-image
  has_stemcell: False
- name: platform-automation-tasks
  has_stemcell: False