#@data/values
---
separate_config: True
pivnet_token: ((pivnet_token))
automation_git_url: https://github.com/rahulkj/pcf-automation
automation_git_branch: master
config_repo_git_url: https://github.com/rahulkj/secrets
config_repo_git_branch: master
locks_git_url: https://github.com/rahulkj/pipeline-locks
locks_git_branch: master
lock_folder: pipeline-lock
git_username: ((git_credentials.username))
git_token: ((git_credentials.password))
credhub_prefix: concourse/homelab
credhub_ca_cert: ((credhub_server_ca.certificate))
credhub_client: ((credhub_client))
credhub_client_secret: ((credhub_client_secret))
credhub_server: ((credhub_server))
smtp_address: ((smtp_address))
smtp_port: ((smtp_port))
smtp_username: ((smtp_credentials.username))
smtp_password: ((smtp_credentials.password))
from_address: ((from_address))
to_addresses: ((to_addresses))
s3_endpoint: http://((s3_endpoint))/
s3_access_key: ((s3_credentials.username))
s3_secret_key: ((s3_credentials.password))
s3_disable_ssl: true
platform_automation_version: ^4\.*\..*$
s3_automation_bucket: automation
s3_automation_image_regex: image/platform-automation-image-(.*).tgz
s3_automation_tasks_regex: tasks/platform-automation-tasks-(.*).zip
apply_changes_config_filename: deploy-products.yml
products:
- name: pks
  slug: pivotal-container-service
  glob: '*.pivotal'
  version: ^1\.7\.[0-9]*$
  has_stemcell: True
  stemcell_version: "621"
  s3_bucket: pks
  s3_stemcell_bucket: stemcells
  s3_product_regex: "(.*).pivotal"
  deploy_product: True
- name: harbor
  slug: harbor-container-registry
  glob: "(.*).pivotal"
  version: ^1\.10\.[0-9]*$
  has_stemcell: True
  stemcell_version: "456"
  s3_bucket: harbor
  s3_stemcell_bucket: stemcells
  s3_product_regex: "(.*).pivotal"
  deploy_product: True
- name: ops-manager
  slug: ops-manager
  glob: '*.ova'
  version: ^2\.9\.[0-9]*$
  has_stemcell: False
  deploy_product: False
- name: pas
  slug: elastic-runtime
  glob: 'cf-*.pivotal'
  version: ^2\.9\.[0-9]*$
  has_stemcell: True
  stemcell_version: "621"
  s3_bucket: pas
  s3_stemcell_bucket: stemcells
  s3_product_regex: "(.*).pivotal"
  deploy_product: False
- name: platform-automation-image
  slug: platform-automation
  glob: '*.tgz'
  version: ^4\.*\..*$
  has_stemcell: False
  deploy_product: False
- name: platform-automation-tasks
  slug: platform-automation
  glob: '*.zip'
  version: ^4\.*\..*$
  has_stemcell: False
  deploy_product: False
