---
platform: linux

params:
  OUTPUT_FILE_NAME:
  PARAM_NAME:

outputs:
- name: output-folder

run:
  path: bash
  args:
  - "-c"
  - |
    set -e
    echo "$PARAM_NAME" > output-folder/$OUTPUT_FILE_NAME
