properties-configuration:
  iaas_configuration:
    name: Site-1
    vcenter_host: ((vcenter_host))
    vcenter_username: ((vcenter_usr))
    vcenter_password: ((vcenter_pwd))
    datacenter: ((vcenter_datacenter))
    disk_type: thick
    ephemeral_datastores_string: ((vcenter_storage))
    persistent_datastores_string: ((vcenter_storage))
    bosh_vm_folder: pcf-vms
    bosh_template_folder: pcf-templates
    bosh_disk_path: pcf-disks
    nsx_networking_enabled: true
    nsx_mode: nsx-t
    nsx_address: ((nsxt_host))
    nsx_username: ((nsxt_username))
    nsx_password: ((nsxt_password))
    nsx_ca_certificate: ((nsx_manager.certificate))

  director_configuration:
    ntp_servers_string: ((ntp_server))
    resurrector_enabled: true
    post_deploy_enabled: true
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    retry_bosh_deploys: false
    keep_unreachable_vms: false
    director_configuration_allow_legacy_agents: true
    max_threads: 8
    director_worker_count: 5
    hm_emailer_options:
      enabled: false
      host: ((smtp_address))
      port: ((smtp_port))
      domain: sendgrid.net
      from: admin@opsmgr.homelab.io
      recipients: ((to_addresses))
      smtp_user: ((smtp_username))
      smtp_password: ((smtp_password))
      tls: true
    hm_pager_duty_options:
      enabled: false
    blobstore_type: local
    database_type: internal

  syslog_configuration:
    enabled: true
    address: ((syslog_host))
    port: ((syslog_port))
    transport_protocol: ((syslog_protocol))
    tls_enabled: false

  security_configuration:
    trusted_certificates: ((pcf_wildcard_certificate.ca))
    opsmanager_root_ca_trusted_certs: true
    generate_vm_passwords: true

az-configuration:
- name: ((az_1_name))
  clusters:
  - cluster: ((az_1_cluster))
    resource_pool: ((az_1_resource_pool))
- name: ((az_2_name))
  clusters:
  - cluster: ((az_2_cluster))
    resource_pool: ((az_2_resource_pool))
- name: ((az_3_name))
  clusters:
  - cluster: ((az_3_cluster))
    resource_pool: ((az_3_resource_pool))

networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: ((infrastructure_network))
    subnets:
    - iaas_identifier: ((infrastructure_network_name))
      cidr: ((infrastructure_network_cidr))
      reserved_ip_ranges: ((infrastructure_network_reserved_ip_ranges))
      dns: ((dns_server))
      gateway: ((infrastructure_network_gateway))
      availability_zone_names:
      - ((az_1_name))
      - ((az_2_name))
      - ((az_3_name))
  - name: ((deploy_network))
    subnets:
    - iaas_identifier: ((deploy_network_name))
      cidr: ((deploy_network_cidr))
      reserved_ip_ranges: ((deploy_network_reserved_ip_ranges))
      dns: ((dns_server))
      gateway: ((deploy_network_gateway))
      availability_zone_names:
      - ((az_2_name))
      - ((az_3_name))
  - name: ((services_network))
    subnets:
    - iaas_identifier: ((services_network_name))
      cidr: ((services_network_cidr))
      reserved_ip_ranges: ((services_network_reserved_ip_ranges))
      dns: ((dns_server))
      gateway: ((services_network_gateway))
      availability_zone_names:
      - ((az_2_name))
      - ((az_3_name))
  - name: ((pks_network))
    subnets:
    - iaas_identifier: ((pks_network_name))
      cidr: ((pks_network_cidr))
      reserved_ip_ranges: ((pks_network_reserved_ip_ranges))
      dns: ((dns_server))
      gateway: ((pks_network_gateway))
      availability_zone_names:
      - ((az_2_name))
      - ((az_3_name))

network-assignment:
  network:
    name: ((infrastructure_network))
  singleton_availability_zone:
    name: ((az_1_name))

resource-configuration:
  director:
    instance_type:
      id: large.disk
    persistent_disk:
      size_mb: "102400"
  compilation:
    instance_type:
      id: large.cpu
    instances: 4

# vmextensions-configuration: []
vmextensions-configuration:
- name: diego-brain-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: ((diego_brain_server_pool_name))
          port: ((diego_brain_server_pool_port))
- name: router-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: ((router_server_pool_name))
          port: ((router_server_pool_port))
- name: istio-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: ((istio_router_server_pool_name))
          port: ((istio_router_server_pool_port))
