properties-configuration:
  iaas_configuration:
    name: Site-1
    vcenter_host: ((vcenter_host))
    vcenter_username: ((vcenter_usr))
    vcenter_password: ((vcenter_pwd))
    datacenter:
    disk_type: thick
    ephemeral_datastores_string:
    persistent_datastores_string:
    bosh_vm_folder: pcf-vms
    bosh_template_folder: pcf-templates
    bosh_disk_path: pcf-disks
    nsx_networking_enabled: true
    nsx_mode: nsx-t
    nsx_address: ((nsxt_host))
    nsx_username: ((nsxt_username))
    nsx_password: ((nsxt_password))
    nsx_ca_certificate: ((nsx_manager.certificate))

  director_configuration:
    ntp_servers_string:
    resurrector_enabled: true
    post_deploy_enabled: true
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    retry_bosh_deploys: false
    keep_unreachable_vms: false
    director_configuration_allow_legacy_agents: true
    max_threads: 8
    director_worker_count: 5
    hm_emailer_options:
      enabled: false
      host:
      port:
      domain:
      from:
      recipients:
      smtp_user:
      smtp_password:
      tls: true
    hm_pager_duty_options:
      enabled: false
    blobstore_type: local
    database_type: internal
    syslog_configuration:
      enabled: true
      address:
      port: 5514
      transport_protocol: tcp
      tls_enabled: false

  security_configuration:
    generate_vm_passwords: true

az-configuration:
- name: MGMT-AZ
  clusters:
  - cluster: PCF
    resource_pool: MGMT_RP
- name: AZ-1
  clusters:
  - cluster: PCF
    resource_pool: PAS_RP
- name: AZ-2
  clusters:
  - cluster: PCF
    resource_pool: SERVICES_RP

networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: INFRASTRUCTURE
    subnets:
    - iaas_identifier: INFRASTRUCTURE
      cidr:
      reserved_ip_ranges:
      dns:
      gateway:
      availability_zone_names:
      - MGMT-AZ
      - AZ-1
      - AZ-2
  - name: DEPLOYMENT
    subnets:
    - iaas_identifier: DEPLOYMENT
      cidr:
      reserved_ip_ranges:
      dns:
      gateway:
      availability_zone_names:
      - AZ-1
      - AZ-2
  - name: SERVICES
    subnets:
    - iaas_identifier: SERVICES
      cidr:
      reserved_ip_ranges:
      dns:
      gateway:
      availability_zone_names:
      - AZ-1
      - AZ-2

network-assignment:
  network:
    name: INFRASTRUCTURE
  singleton_availability_zone:
    name: MGMT-AZ

resource-configuration:
  director:
    instance_type:
      id: large.disk
    persistent_disk:
      size_mb: "102400"
  compilation:
    instance_type:
      id: large.cpu
    instances: 4

## OPTIONAL
vmextensions-configuration:
- name: diego-brain-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: PAS-DiegoBrain2222ServerPool
          port: 2222
- name: router-extension
  cloud_properties:
    nsxt:
      lb:
        server_pools:
        - name: PAS-GoRouter443ServerPool
          port: 443
