---

platform: linux

params:
  DEBUG:
  ENV_FILE:
  PRODUCT_NAME:
  DEPENDENCY_PRODUCT_TILES:

inputs:
- name: pipelines-repo
- name: om-cli
- name: pivnet-product
- name: env
- name: jq

run:
  path: pipelines-repo/tasks/stage-product/task.sh
