resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: tile-config-convertor
  type: github-release
  source:
    user: rahul-kj
    repository: tile-config-convertor
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: secrets-repo
  type: git
  source:
    uri: ((secrets_git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: automation-repo
  type: git
  source:
    uri: ((automation_git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((opsman_product_version))

- name: pas-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((pas_product_version))

- name: nsxt-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: vmware-nsx-t
    product_version: ((nsxt_product_version))

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: email
  type: email
  source:
    smtp:
      host: ((smtp_address))
      port: ((smtp_port))
      username: ((smtp_username))
      password: ((smtp_password))
    from: ((from_address))
    to: [((to_addresses))]

credhub-interpolate: &credhub-interpolate-env
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: secrets-repo
  output_mapping:
    interpolated-files: env
  params:
    PREFIX: ((credhub_prefix))
    CREDHUB_CA_CERT: ((credhub_server_ca.certificate))
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_client_secret))
    CREDHUB_SERVER: ((credhub_server))
    INTERPOLATION_PATH: ((opsman_env_path))

credhub-interpolate: &credhub-interpolate-config
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: secrets-repo
  output_mapping:
    interpolated-files: config
  params:
    PREFIX: ((credhub_prefix))
    CREDHUB_CA_CERT: ((credhub_server_ca.certificate))
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_client_secret))
    CREDHUB_SERVER: ((credhub_server))
    INTERPOLATION_PATH: ((product_config_path))

cli-params: &cli-params
  params:
    globs:
    - "*linux*64*"

jobs:
- name: generate-ops-manager-config
  plan:
  - aggregate:
    - get: automation-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: secrets-repo
    - get: govc
      <<: *cli-params
    - get: pivnet-product
      resource: ops-manager
      params:
        globs:
        - ((opsman_glob))

  - task: generate-config
    file: automation-repo/tasks/generate-opsman-config/task.yml
    params:
      DEBUG: ((debug))

- name: install-ops-manager
  plan:
  - aggregate:
    - get: secrets-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: pivnet-product
      resource: ops-manager
      params:
        globs:
        - ((opsman_glob))

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: credhub-interpolate-config
    <<: *credhub-interpolate-config

  - task: deploy-opsmanager-vm
    image: platform-automation-image
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      state: secrets-repo
      image: pivnet-product
      config: config
    params:
      OPSMAN_CONFIG_FILE: ((product_config_path))/((opsman_config_filename))
      STATE_FILE: ((state_filename))

  - task: commit-files-into-git
    image: platform-automation-image
    file: platform-automation-tasks/tasks/make-git-commit.yml
    input_mapping:
      repository: secrets-repo
      file-source: generated-state
    params:
      FILE_SOURCE_PATH: ((state_filename))
      FILE_DESTINATION_PATH: ((state_file_destination))/((state_filename))
      GIT_AUTHOR_NAME: ((ci_username))
      GIT_AUTHOR_EMAIL: ((ci_email_address))
      COMMIT_MESSAGE: "Updated state file after creating the OpsManager VM"

  - task: configure-authentication
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-authentication.yml
    input_mapping:
      config: config
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      AUTH_CONFIG_FILE: ((product_config_path))/((opsman_auth_filename))
    attempts: 20

  - put: secrets-repo
    params:
      repository: repository-commit

- name: configure-ops-director
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [install-ops-manager]
    - get: platform-automation-image
      passed: [install-ops-manager]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [install-ops-manager]
    - get: pivnet-product
      resource: ops-manager
      params:
        globs: []
      trigger: true
      passed: [install-ops-manager]

  - task: credhub-interpolate-config
    <<: *credhub-interpolate-config

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: configure-ops-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      DIRECTOR_CONFIG_FILE: ((product_config_path))/((ops_director_config_filename))

- name: deploy-director
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [configure-ops-director]
    - get: platform-automation-image
      passed: [configure-ops-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-ops-director]
    - get: pivnet-product
      resource: ops-manager
      params:
        globs: []
      trigger: true
      passed: [configure-ops-director]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: deploy-ops-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: upload-nsxt
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [configure-ops-director]
    - get: platform-automation-image
      passed: [configure-ops-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-ops-director]
    - get: nsxt-product
      params:
        globs: [((nsxt_product_glob))]
      trigger: true

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: upload-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: nsxt-product
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: upload-pas
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [configure-ops-director]
    - get: automation-repo
    - get: platform-automation-image
      passed: [configure-ops-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-ops-director]
    - get: pas-product
      params:
        globs: [((pas_product_glob))]
      trigger: true
    - get: jq
      <<: *cli-params
    - get: pivnet-cli
      <<: *cli-params
    - get: om-cli
      <<: *cli-params

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: upload-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: pas-product
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

  - task: download-stemcell
    image: platform-automation-image
    file: automation-repo/tasks/download-stemcell/task.yml
    input_mapping:
      product: pas-product
    params:
      DEBUG: ((debug))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      STEMCELL_TYPE: ((stemcell_type))

  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: stemcells
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: stage-nsxt
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [upload-nsxt]
    - get: platform-automation-image
      passed: [upload-nsxt, deploy-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [upload-nsxt, deploy-director]
    - get: nsxt-product
      params:
        globs: [((nsxt_product_glob))]
      trigger: true
      passed: [upload-nsxt]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: nsxt-product
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: generate-nsxt-config
  plan:
  - aggregate:
    - get: platform-automation-image
      passed: [stage-nsxt]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: secrets-repo
      passed: [stage-nsxt]
    - get: automation-repo
    - get: pivnet-product
      resource: nsxt-product
      params:
        globs: []
      passed: [stage-nsxt]
    - get: om-cli
      <<: *cli-params
    - get: jq
      <<: *cli-params
    - get: tile-config-convertor
      <<: *cli-params

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: generate-config
    image: platform-automation-image
    file: automation-repo/tasks/generate-config/task.yml
    input_mapping:
      env: env
    params:
      DEBUG: ((debug))
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      PRODUCT_NAME: ((nsxt_product_identifier))

- name: configure-nsxt
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [stage-nsxt]
    - get: platform-automation-image
      passed: [stage-nsxt]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [stage-nsxt]
    - get: nsxt-product
      params:
        globs: []
      trigger: true
      passed: [stage-nsxt]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: credhub-interpolate-config
    <<: *credhub-interpolate-config

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config
      env: env
    params:
      CONFIG_FILE: ((product_config_path))/((nsxt_config_filename))
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: stage-pas
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [configure-nsxt]
    - get: platform-automation-image
      passed: [configure-nsxt]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-nsxt]
    - get: pas-product
      params:
        globs: [((pas_product_glob))]
      trigger: true
      passed: [upload-pas]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: pas-product
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: generate-pas-config
  plan:
  - aggregate:
    - get: platform-automation-image
      passed: [stage-pas]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: secrets-repo
      passed: [stage-pas]
    - get: automation-repo
    - get: pivnet-product
      resource: pas-product
      params:
        globs: []
      passed: [stage-pas]
    - get: om-cli
      <<: *cli-params
    - get: jq
      <<: *cli-params
    - get: tile-config-convertor
      <<: *cli-params

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: generate-config
    image: platform-automation-image
    file: automation-repo/tasks/generate-config/task.yml
    input_mapping:
      env: env
    params:
      DEBUG: ((debug))
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      PRODUCT_NAME: ((pas_product_identifier))

- name: configure-pas
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [stage-pas]
    - get: platform-automation-image
      passed: [stage-pas]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [stage-pas]
    - get: pas-product
      params:
        globs: []
      trigger: true
      passed: [stage-pas]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: credhub-interpolate-config
    <<: *credhub-interpolate-config

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config
      env: env
    params:
      CONFIG_FILE: ((product_config_path))/((pas_config_filename))
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: secrets-repo
      passed: [configure-pas]
    - get: platform-automation-image
      passed: [configure-pas, configure-nsxt]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-pas, configure-nsxt]
    - get: pas-product
      params:
        globs: []
      trigger: true
      passed: [configure-pas]
    - get: nsxt-product
      params:
        globs: []
      trigger: true
      passed: [configure-nsxt]

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: deploy-pas
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"

## Remove this if you don't need it in your pipeline
- name: delete-all
  plan:
  - aggregate:
    - get: secrets-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: ops-manager
      params:
        globs: []

  - task: credhub-interpolate-env
    <<: *credhub-interpolate-env

  - task: credhub-interpolate-config
    <<: *credhub-interpolate-config

  - task: delete-products
    image: platform-automation-image
    file: platform-automation-tasks/tasks/delete-installation.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

  - task: delete-opsmanager-vm
    image: platform-automation-image
    file: platform-automation-tasks/tasks/delete-vm.yml
    input_mapping:
      state: secrets-repo
      config: config
    params:
      STATE_FILE: ((state_file_destination))/((state_filename))
      OPSMAN_CONFIG_FILE: ((product_config_path))/((opsman_config_filename))

  - task: commit-files-into-git
    image: platform-automation-image
    file: platform-automation-tasks/tasks/make-git-commit.yml
    input_mapping:
      repository: secrets-repo
      file-source: generated-state
    params:
      FILE_SOURCE_PATH: ((state_filename))
      FILE_DESTINATION_PATH: ((state_file_destination))/((state_filename))
      GIT_AUTHOR_NAME: ((ci_username))
      GIT_AUTHOR_EMAIL: ((ci_email_address))
      COMMIT_MESSAGE: "Updated state file after deleting the OpsManager VM"

  - put: secrets-repo
    params:
      repository: repository-commit

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
