#@ load("@ytt:data", "data")
resources:
- name: schedule
  type: time
  source:
    interval: 24h
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: automation-repo
  type: git
  source:
    uri: ((automation_git_url))
    branch: ((automation_git_branch))
    username: ((git_username))
    password: ((git_token))

- name: locks
  type: pool
  source:
    uri: ((locks_git_url))
    branch: ((locks_git_branch))
    username: ((git_username))
    password: ((git_token))
    pool: ((env_lock_folder))

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

#@ for product in data.values.products:
- name: #@ product.name
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: #@ product.slug
    product_version: #@ product.version
    sort_by: semver

#@ if/end product.has_stemcell == True:
- name: #@ product.name + "-stemcells"
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: #@ product.stemcell_slug
    product_version: #@ product.stemcell_version
    sort_by: semver
#@ end

groups:
- name: all
  jobs:
  - scheduler
  - unset-lock
  #@ for product in data.values.products:
  #@ if data.values.separate_config == True:
  - #@ "lock-upload-stage-" + product.name
  - #@ "configure-deploy-unlock-" + product.name
  #@ else:
  - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
  #@ end
  - #@ "run-errand-" + product.name
  #@ end
#@ for product in data.values.products:
- name: #@ product.name
  jobs:
  #@ if data.values.separate_config == True:
  - #@ "lock-upload-stage-" + product.name
  - #@ "configure-deploy-unlock-" + product.name
  #@ else:
  - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
  #@ end
  - #@ "run-errand-" + product.name
#@ end

jobs:
- name: scheduler
  plan:
  - get: schedule
    trigger: true

#@ for product in data.values.products:
#@ index=data.values.products.index(product)
#@ if index != 0:
#@  product_prev=data.values.products[index-1]
#@ end
#@ if data.values.separate_config == True:
#@   job_name="lock-upload-stage-" + product.name
#@   config_job_name="configure-deploy-unlock-"
#@ else:
#@   job_name="lock-upload-stage-configure-deploy-unlock-" + product.name
#@   config_job_name="lock-upload-stage-configure-deploy-unlock-"
#@ end
- name: #@ job_name
  serial: true
  plan:
  - in_parallel:
    - get: schedule
      #@ if index != 0:
      passed:
      - #@ config_job_name + product_prev.name
      #@ else:
      passed:
      - scheduler
      #@ end
    - get: automation-repo
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: product
      resource: #@ product.name
      params:
        globs:
        - #@ product.product_glob
      trigger: true
    #@ if/end product.has_stemcell == True:
    - get: #@ product.name + "-stemcells"
      params:
        globs:
        - #@ product.stemcell_glob
      trigger: true
    - put: locks
      params: {acquire: true}

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: automation-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub_prefix))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_client_secret))
      CREDHUB_SERVER: ((credhub_server))
      INTERPOLATION_PATHS: ((opsman_env_path))

  - in_parallel:
    - task: upload-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-product.yml
      input_mapping:
        product: product
        env: env
      params:
        ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

    #@ if/end product.has_stemcell == True:
    - task: upload-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcells
        env: env
      params:
        ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: product
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

#@ if data.values.separate_config != True:
  - task: create-product-var-files
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: automation-repo
    output_mapping:
      interpolated-files: vars
    params:
      PREFIX: ((credhub_prefix))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_client_secret))
      CREDHUB_SERVER: ((credhub_server))
      INTERPOLATION_PATHS: #@ "((" + product.name + "_vars_path))"
      SKIP_MISSING: true

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: automation-repo
      env: env
      vars: vars
    params:
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      VARS_FILES: #@ "((vars_folder))/((" + product.name + "_vars_path))/((" + product.name + "_var_filename))"

  - task: deploy-product
    file: automation-repo/tasks/apply-product-changes.yml
    input_mapping:
      env: env
      config: automation-repo
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
    attempts: ((attempts))

  - put: locks
    params: {release: locks}
#@ else:
- name: #@ "configure-deploy-unlock-" + product.name
  serial: true
  plan:
  - in_parallel:
    - get: automation-repo
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: product
      resource: #@ product.name
      passed:
      - #@ "lock-upload-stage-" + product.name
      trigger: true
    - get: schedule
      passed:
      - #@ "lock-upload-stage-" + product.name    
    #@ if/end product.has_stemcell == True:
    - get: #@ product.name + "-stemcells"
      passed:
      - #@ "lock-upload-stage-" + product.name
      trigger: true
      params:
        skip_download: "true"
    - put: locks
      params: {acquire: locks}

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: automation-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub_prefix))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_client_secret))
      CREDHUB_SERVER: ((credhub_server))
      INTERPOLATION_PATHS: ((opsman_env_path))

  - task: create-product-var-files
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: automation-repo
    output_mapping:
      interpolated-files: vars
    params:
      PREFIX: ((credhub_prefix))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_client_secret))
      CREDHUB_SERVER: ((credhub_server))
      INTERPOLATION_PATHS: ((product_vars_path))
      SKIP_MISSING: true

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: automation-repo
      env: env
      vars: vars
    params:
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      VARS_FILES: #@ "((vars_folder))/((" + product.name + "_vars_path))/((" + product.name + "_var_filename))"

  - task: deploy-product
    file: automation-repo/tasks/apply-changes.yml
    input_mapping:
      env: env
      config: coautomationnfig-repo
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      APPLY_CHANGES_CONFIG: #@ "((" + product.name + "_config_path))/((apply_changes_config_filename))"
    attempts: ((attempts))

  - put: locks
    params: {release: locks}
#@ end
#@ end

#@ for product in data.values.products:
- name: #@ "run-errand-" + product.name
  serial: true
  plan:
  - in_parallel:
    - get: automation-repo
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: product
      resource: #@ product.name
      params:
        globs: []
      #@ if data.values.separate_config == True:
      passed:
      - #@ "configure-deploy-unlock-" + product.name
      #@ else:
      passed:
      - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
      #@ end
      trigger: true
    #@ if product.has_stemcell == True:
    - get: #@ product.name + "-stemcells"
      #@ if data.values.separate_config == True:
      passed:
      - #@ "configure-deploy-unlock-" + product.name
      #@ else:
      passed:
      - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
      #@ end
      trigger: true
      params:
        globs: []
    #@ end

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: automation-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub_prefix))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_client_secret))
      CREDHUB_SERVER: ((credhub_server))
      INTERPOLATION_PATHS: ((opsman_env_path))

  - task: run-product-errands
    image: platform-automation-image
    file: automation-repo/tasks/run-errands.yml
    input_mapping:
      config: automation-repo
      env: env
    params:
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      ERRAND_FILE: #@ "((" + product.name + "_errand_file))"
      OPSMAN_SSH_PRIVATE_KEY: ((opsman_ssh_private_key))
      INSTANCE: #@ "((" + product.name + "_errand_execution_job))"
#@ end

- name: unset-lock
  plan:
  - get: locks
  - put: locks
    params: {release: locks}
