product-name: p-healthwatch

network-properties:
  network:
    name: SERVICES
  service_network:
    name: SERVICES
  other_availability_zones:
    - name: AZ-1
    - name: AZ-2
  singleton_availability_zone:
    name: AZ-2

product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: 1
  .healthwatch-forwarder.boshtasks_instance_count:
    value: 1
  .healthwatch-forwarder.canary_instance_count:
    value: 1
  .healthwatch-forwarder.cli_instance_count:
    value: 1
  .healthwatch-forwarder.foundation_name:                                                              # OPTIONAL
    value: HOMELAB
  .healthwatch-forwarder.health_check_az:
    value: AZ-2
  .healthwatch-forwarder.health_check_vm_type:
    value: nano
  .healthwatch-forwarder.ingestor_instance_count:
    value: 1
  .healthwatch-forwarder.opsman_instance_count:
    value: 1
  .healthwatch-forwarder.publish_to_eva:
    value: true
  .healthwatch-forwarder.worker_instance_count:
    value: 1
  .mysql.skip_name_resolve:
    value: true
  .properties.boshtasks:
    value: disable
  .properties.opsman:
    value: enable
  .properties.opsman.enable.url:
    value: https://((ops_mgr_host))
  .properties.syslog_selector:
    value: "No"

resource-config:
  healthwatch-forwarder:
    instances: 2
    instance_type:
      id: xlarge
    persistent_disk:
      size_mb: "102400"
  redis:
    instances: 1
    instance_type:
      id: xlarge
    persistent_disk:
      size_mb: "102400"
  mysql:
    instances: 1
    instance_type:
      id: 2xlarge
    persistent_disk:
      size_mb: "102400"
