product-name: p-healthwatch

network-properties:
  network:
    name: ((network_name))
  service_network:
    name: ((service_network_name))
  other_availability_zones:
    - name: ((az_1_name))
    - name: ((az_2_name))
  singleton_availability_zone:
    name: ((singleton_availability_zone_name))

product-properties:
  .healthwatch-forwarder.foundation_name:
    value: ((foundation_name))
  .healthwatch-forwarder.health_check_az:
    value: ((health_check_az_name))
  .properties.boshtasks:
    value: disable
  .properties.opsman:
    value: enable
  .properties.opsman.enable.url:
    value: https://((opsman_host))
  .properties.syslog_selector:
    value: "No"

resource-config:
  healthwatch-forwarder:
    instances: 2
    instance_type:
      id: xlarge
    persistent_disk:
      size_mb: "102400"
  redis:
    instances: 1
    instance_type:
      id: xlarge
    persistent_disk:
      size_mb: "102400"
  mysql:
    instances: 1
    instance_type:
      id: 2xlarge
    persistent_disk:
      size_mb: "102400"
