resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: tile-config-convertor
  type: github-release
  source:
    user: rahul-kj
    repository: tile-config-convertor
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: git-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((opsman_product_version))

- name: pas-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((pas_product_version))

- name: email
  type: email
  source:
    smtp:
      host: ((smtp_address))
      port: ((smtp_port))
      username: ((smtp_username))
      password: ((smtp_password))
    from: ((from_address))
    to: [((to_addresses))]

jobs:
- name: install-ops-manager
  plan:
  - aggregate:
    - get: git-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: pivnet-product
      resource: ops-manager
      params:
        globs:
        - ((opsman_glob))

  - task: create-opsman-import-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: opsman.yml
      PARAM_NAME: ((ops_manager_settings))

  - task: deploy-opsmanager-vm
    image: platform-automation-image
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      state: git-repo
      image: pivnet-product
      config: output-folder

  - task: commit-files-into-git
    image: platform-automation-image
    file: platform-automation-tasks/tasks/make-git-commit.yml
    input_mapping:
      repository: git-repo
      file-source: generated-state
    params:
      FILE_SOURCE_PATH: ((state_file_name))
      FILE_DESTINATION_PATH: ((state_file_destination))/((state_file_name))
      GIT_AUTHOR_NAME: ((ci_username))
      GIT_AUTHOR_EMAIL: ((ci_email_address))
      COMMIT_MESSAGE: "Updated state file after creating the OpsManager VM"

  - put: git-repo
    params:
      repository: repository-commit

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: create-opsman-auth-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: auth
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_auth_filename))
      PARAM_NAME: ((ops_manager_auth))

  - task: configure-authentication
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-authentication.yml
    input_mapping:
      config: auth
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))
      AUTH_CONFIG_FILE: ((opsman_auth_filename))
    attempts: 20

- name: configure-ops-director
  plan:
  - aggregate:
    - get: git-repo
      passed: [install-ops-manager]
    - get: platform-automation-image
      passed: [install-ops-manager]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [install-ops-manager]
    - get: pivnet-product
      resource: ops-manager
      params:
        globs: []
      trigger: true
      passed: [install-ops-manager]

  - task: create-ops-director-config-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: config
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: director.yml
      PARAM_NAME: ((ops_dir_configuration))

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: configure-ops-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    params:
      ENV_FILE: ((opsman_env_filename))
      DIRECTOR_CONFIG_FILE: director.yml

- name: deploy-director
  plan:
  - aggregate:
    - get: git-repo
      passed: [configure-ops-director]
    - get: platform-automation-image
      passed: [configure-ops-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-ops-director]
    - get: pivnet-product
      resource: ops-manager
      params:
        globs: []
      trigger: true
      passed: [configure-ops-director]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: deploy-ops-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

- name: upload-pas
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [configure-ops-director]
    - get: platform-automation-image
      passed: [configure-ops-director]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-ops-director]
    - get: pas-product
      params:
        globs: [((pas_product_glob))]
      trigger: true
    - get: jq
      params:
        globs:
        - "*linux64*"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
    - get: om-cli
      params:
        globs:
        - "*-linux"

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: upload-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: pas-product
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

  - task: download-stemcell
    image: platform-automation-image
    file: git-repo/tasks/download-stemcell/task.yml
    input_mapping:
      product: pas-product
    params:
      DEBUG: ((debug))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      STEMCELL_TYPE: ((stemcell_type))

  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: stemcells
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

- name: stage-pas
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [upload-pas]
    - get: platform-automation-image
      passed: [upload-pas]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [upload-pas]
    - get: pas-product
      params:
        globs: [((pas_product_glob))]
      trigger: true
      passed: [upload-pas]
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [upload-pas]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-pas]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-pas]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: pas-product
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

- name: generate-pas-config
  plan:
  - aggregate:
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
      passed: [stage-pas]
    - get: git-repo
      passed: [stage-pas]
    - get: pivnet-product
      resource: pas-product
      params:
        globs: []
      passed: [stage-pas]
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [stage-pas]
    - get: tile-config-convertor
      params:
        globs: ["*linux*"]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: generate-config
    image: platform-automation-image
    file: git-repo/tasks/generate-config/task.yml
    input_mapping:
      env: env
    params:
      DEBUG: ((debug))
      ENV_FILE: ((opsman_env_filename))
      PRODUCT_NAME: ((pas_product_identifier))

- name: generate-certificates
  plan:
  - aggregate:
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
      passed: [stage-pas]
    - get: git-repo
      passed: [stage-pas]
    - get: pivnet-product
      resource: pas-product
      params:
        globs: []
      passed: [stage-pas]
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [stage-pas]
    - get: tile-config-convertor
      params:
        globs: ["*linux*"]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: generate-certificates
    image: platform-automation-image
    file: git-repo/tasks/generate-certs/task.yml
    input_mapping:
      env: env
    params:
      DEBUG: ((debug))
      ENV_FILE: ((opsman_env_filename))
      DOMAINS: ((wildcard_domains))

- name: configure-pas
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [stage-pas]
    - get: platform-automation-image
      passed: [stage-pas]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [stage-pas]
    - get: pas-product
      params:
        globs: []
      trigger: true
      passed: [stage-pas]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: create-pas-config-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: config
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: pas-config.yml
      PARAM_NAME: ((pas_config))

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config
      env: env
    params:
      CONFIG_FILE: pas-config.yml
      ENV_FILE: ((opsman_env_filename))

- name: deploy-pas
  serial: true
  plan:
  - aggregate:
    - get: git-repo
      passed: [configure-pas]
    - get: platform-automation-image
      passed: [configure-pas]
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
      passed: [configure-pas]
    - get: pas-product
      params:
        globs: []
      trigger: true
      passed: [configure-pas]

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: deploy-pas
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

## Remove this if you don't need it in your pipeline
- name: delete-all
  plan:
  - aggregate:
    - get: git-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: ops-manager
      params:
        globs: []

  - task: create-opsman-env-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: env
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: ((opsman_env_filename))
      PARAM_NAME: ((ops_manager_env))

  - task: create-opsman-import-file
    image: platform-automation-image
    file: git-repo/tasks/create-yml-file/task.yml
    output_mapping:
      output-folder: config
    params:
      DEBUG: ((debug))
      OUTPUT_FILE_NAME: opsman.yml
      PARAM_NAME: ((ops_manager_settings))

  - task: delete-products
    image: platform-automation-image
    file: git-repo/tasks/delete-installation.yml
    input_mapping:
      env: env
    params:
      ENV_FILE: ((opsman_env_filename))

  - task: delete-opsmanager-vm
    image: platform-automation-image
    file: git-repo/tasks/delete-vm.yml
    input_mapping:
      state: git-repo
      config: config
    params:
      STATE_FILE: ((state_file_destination))/((state_file_name))

  - task: commit-files-into-git
    image: platform-automation-image
    file: git-repo/tasks/make-git-commit.yml
    input_mapping:
      repository: git-repo
      file-source: generated-state
    params:
      FILE_SOURCE_PATH: ((state_file_name))
      FILE_DESTINATION_PATH: ((state_file_destination))/((state_file_name))
      GIT_AUTHOR_NAME: ((ci_username))
      GIT_AUTHOR_EMAIL: ((ci_email_address))
      COMMIT_MESSAGE: "Updated state file after deleting the OpsManager VM"

  - put: git-repo
    params:
      repository: repository-commit

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
