#@ load("@ytt:data", "data")
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: custom-docker-image
  type: docker-image
  source:
    repository: rjain/buildbox

- name: automation-repo
  type: git
  source:
    uri: ((automation_git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

#@ for product in data.values.products:
- name: #@ product.name
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: #@ product.slug
    product_version: #@ product.version
    sort_by: semver

- name: #@ product.name + "-product-bucket"
  type: s3
  source:
    endpoint: ((s3_endpoint))
    bucket: #@ product.s3_bucket
    regexp: #@ product.s3_product_regex
    access_key_id: ((s3_access_key))
    secret_access_key: ((s3_secret_key))
    disable_ssl: ((s3_disable_ssl))

#@ if product.has_stemcell == True:
- name: #@ product.name + "-stemcells"
  type: s3
  source:
    endpoint: ((s3_endpoint))
    bucket: #@ product.s3_bucket
    regexp: stemcells/((s3_stemcells_regex))
    access_key_id: ((s3_access_key))
    secret_access_key: ((s3_secret_key))
    disable_ssl: ((s3_disable_ssl))
#@ end
#@ end

jobs:
#@ for/end product in data.values.products:
- name: #@ product.name
  plan:
  - in_parallel:
    #@ if/end product.has_stemcell == True:
    - get: automation-repo
    #@ if/end product.has_stemcell == True:
    - get: custom-docker-image
    - get: product
      resource: #@ product.name
      trigger: true
      params:
        globs:
        - #@ product.glob

  - put: #@ product.name + "-product-bucket"
    params:
      file: #@ "product/" + product.glob

  #@ if/end product.has_stemcell == True:
  - task: download-stemcell
    image: custom-docker-image
    file: automation-repo/tasks/download-stemcell/task.yml
    params:
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      STEMCELL_TYPE: ((stemcell_type))
  #@ if/end product.has_stemcell == True:
  - put: #@ product.name + "-stemcells"
    params:
      file: stemcells/*.tgz
