#@data/values
---
pivnet_token: ""
s3_endpoint: http://((s3_endpoint))/
s3_access_key: ""
s3_secret_key: ""
s3_disable_ssl: true

products:
- name: ops-manager
  has_stemcell: False
- name: pas
  has_stemcell: True
- name: pks
  has_stemcell: True
- name: harbor
  has_stemcell: True
- name: platform-automation-image
  has_stemcell: False
- name: platform-automation-tasks
  has_stemcell: False
