pivnet_token: ((pivnet_token))
platform_automation_version: 0.0.1-rc.130
healthwatch_version: 1.3.2

# The token used to download the repos from GitHub for the pipelines
git_token: ((git_token))
git_url: https://github.com/rahul-kj/test-automation # [R] Pipelines github repo
git_branch: master
git_username: ((git_username)) # [R] Your github username
