resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-image
  type: docker-image
  source:
    repository: pivotalservices/platform-automation
    tag: 0.0.1-rc.130
- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
- name: healthwatch-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: p-healthwatch
    product_version: ((healthwatch_version))
- name: config-repo
  type: git
  source:
    uri: https://github.com/rahul-kj/test-automation.git
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))
- name: pipeline-utilities
  type: git
  source:
    uri: https://github.com/pivotalservices/pipeline-utilities.git

jobs:
- name: upload-and-stage-healthwatch
  plan:
  - aggregate:
    - get: pipeline-utilities
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        globs:
        - "*.zip"
        unpack: true
    - get: config-repo
      trigger: true
    - get: healthwatch-product
      params:
        globs: ["*.pivotal"]

  - aggregate:
    - task: create-om-env
      file: pipeline-utilities/tasks/create-om-env.yml
      params:
        OPSMAN_TARGET: ((ops_mgr_host))
        OPSMAN_SKIP_SSL_VALIDATION: true
        OPSMAN_USERNAME: ((ops_mgr_usr))
        OPSMAN_PASSWORD: ((ops_mgr_pwd))

  - task: upload-and-stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-and-stage-product.yml
    input_mapping:
      config: config-repo
      product: healthwatch-product

- name: configure-healthwatch
  plan:
  - aggregate:
    - get: pipeline-utilities
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        globs:
        - "*.zip"
        unpack: true
    - get: config-repo
      params:
        unpack: true
      passed: [upload-and-stage-healthwatch]
      trigger: true
    - get: healthwatch-product
      params:
        globs: ["*.pivotal"]
  - aggregate:
    - task: create-om-env
      file: pipeline-utilities/tasks/create-om-env.yml
      params:
        OPSMAN_TARGET: ((ops_mgr_host))
        OPSMAN_SKIP_SSL_VALIDATION: true
        OPSMAN_USERNAME: ((ops_mgr_usr))
        OPSMAN_PASSWORD: ((ops_mgr_pwd))

  - task: configure-healthwatch
    input_mapping:
      product: healthwatch-product
      config: config-repo
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    params:
      CONFIG_FILE: healthwatch/healthwatch.yml

- name: apply-product-changes
  plan:
  - aggregate:
    - get: pipeline-utilities
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        globs:
        - "*.zip"
        unpack: true
    - get: config-repo
      passed:
      - configure-healthwatch
      trigger: true
  - aggregate:
    - task: create-om-env
      file: pipeline-utilities/tasks/create-om-env.yml
      params:
        OPSMAN_TARGET: ((ops_mgr_host))
        OPSMAN_SKIP_SSL_VALIDATION: true
        OPSMAN_USERNAME: ((ops_mgr_usr))
        OPSMAN_PASSWORD: ((ops_mgr_pwd))
  - task: apply-product-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
