---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  ENV_FILE:
  CONFIG_FILE:

inputs:
  - name: git-repo
  - name: tile-config-convertor
  - name: env
  - name: config

run:
  path: git-repo/tasks/generate-config/task.sh
