---

platform: linux

params:
  ENV_FILE:
  PRODUCT_NAME:

inputs:
  - name: git-repo
  - name: om-cli
  - name: jq
  - name: tile-config-convertor
  - name: env

run:
  path: git-repo/tasks/generate-config/task.sh
