---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  PRODUCT_IDENTIFIER:
  PRODUCT_PROPERTIES:
  PRODUCT_RESOURCES:
  PRODUCT_NETWORK_AZS:

inputs:
  - name: pipelines-repo
  - name: jq

run:
  path: pipelines-repo/tasks/output-properties/task.sh
